import type { UIText } from './zhTW';

export const enUSText = {
  nav: {
    dashboard: 'Dashboard',
    tasks: 'Tasks',
    search: 'Search',
    settings: 'Settings',
    agent: 'Agent',
    language: 'Language',
  },
  language: {
    'zh-TW': 'Traditional Chinese',
    'en-US': 'English',
  },
  dashboard: {
    title: 'Dashboard',
    createTask: 'Create Task',
    taskList: 'Task List',
    refresh: 'Refresh',
    openManager: 'Open task manager',
    adapterCapabilities: 'Adapter capabilities',
    verificationCapability: 'Human verification',
    metadataCapability: 'Manga metadata',
    chapterImagesCapability: 'Chapter images',
    noAdapters: 'No adapters loaded.',
  },
  taskForm: {
    urlLabel: 'URL',
    allChaptersMode: 'All chapters',
    allChaptersDescription: 'Enter a manga page URL. ComicCrawler fetches metadata and the chapter list, then downloads every chapter image.',
    specificChaptersMode: 'Specific chapters',
    specificChaptersDescription: 'Enter one or more chapter page URLs. ComicCrawler downloads those chapter images directly without expanding the whole manga.',
    mangaUrlLabel: 'Manga URL',
    mangaUrlHelp: 'Example: https://kuronavi.one/manga/an-haxing-jian-guo-jia-noe-de-ling-zhu/',
    chapterUrlsLabel: 'Chapter URLs',
    chapterUrlLabel: 'Chapter URL',
    chapterUrlsHelp: 'Enter one chapter page URL per field. Click + to add another chapter URL.',
    addChapterUrl: 'Add chapter URL',
    removeChapterUrl: 'Remove chapter URL',
    chaptersLabel: 'Chapter filter (optional, comma-separated)',
    chaptersPlaceholder: 'Example: chapter-1, Chapter 0, preview, #3',
    chaptersHelp: 'Leave empty to download every extracted chapter. You can enter chapter IDs, title keywords, URL fragments, or #3 for the third extracted item.',
    priorityLabel: 'Priority',
    priorityHelp: 'Only affects queue order. Higher numbers run earlier; it does not change what gets downloaded.',
    showAdvanced: 'Show advanced options',
    hideAdvanced: 'Hide advanced options',
    submit: 'Create Task',
    submitting: 'Creating...',
    created: 'Task created.',
    viewTask: 'View task',
    discoveryQueued: 'No usable adapter was found. Selector discovery has been queued.',
    capabilityMismatch: 'Existing adapter capability does not match this task',
    openDiscovery: 'Open URL Onboarding to inspect discovery status',
  },
  taskList: {
    id: 'ID',
    url: 'URL',
    status: 'Status',
    priority: 'Priority',
    actions: 'Actions',
    progress: 'Progress',
    empty: 'No tasks yet.',
    pause: 'Pause',
    resume: 'Resume',
    cancel: 'Cancel',
    delete: 'Delete',
    view: 'View',
    statusLabels: {
      pending: 'Pending',
      running: 'Running',
      waiting_verification: 'Waiting for human verification',
      completed: 'Completed',
      failed: 'Failed',
      paused: 'Paused',
      cancelled: 'Cancelled',
      interrupted: 'Interrupted',
    },
  },
  taskManager: {
    title: 'Task Manager',
    description: 'Inspect every task, review progress snapshots, and preview downloaded files.',
    listTitle: 'All Tasks',
    detailTitle: 'Task Details',
    emptyState: 'Select a task to inspect its details.',
    noPreview: 'No downloaded file preview is available for this task yet.',
    previewTitle: 'Download Preview',
    outputPath: 'Output Path',
    metadataTitle: 'Metadata Title',
    downloadedImages: 'Downloaded Images',
    failedImages: 'Failed Images',
    totalImages: 'Total Images',
    currentItem: 'Current Item',
    createdAt: 'Created',
    startedAt: 'Started',
    completedAt: 'Completed',
    error: 'Error',
    files: 'Files',
    refresh: 'Refresh',
  },
  stats: {
    loading: 'Loading...',
    total: 'All Tasks',
    running: 'Running',
    waitingVerification: 'Waiting Verification',
    pending: 'Pending',
    interrupted: 'Interrupted',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
  },
  search: {
    title: 'Search Comics',
    placeholder: 'Enter a keyword...',
    submit: 'Search',
    submitting: 'Searching...',
    empty: 'No results found.',
    historyTitle: 'Recent searches',
  },
  settings: {
    title: 'Settings',
    loading: 'Loading...',
    dismissError: 'Dismiss error',
    languageSection: 'Interface Language',
    languageLabel: 'Display Language',
    fallbackLabel: 'Fallback Language',
    downloadSection: 'Download Settings',
    downloadDirectory: 'Download Directory',
    downloadConcurrency: 'Download Concurrency',
    namingTemplate: 'Naming Template',
    imageFormat: 'Image Format',
    originalFormat: 'Keep original format',
    networkSection: 'Network Settings',
    timeout: 'Timeout (ms)',
    retries: 'Retry Count',
    retryDelay: 'Retry Delay (ms)',
    save: 'Save',
    reset: 'Reset to Defaults',
  },
  agent: {
    eyebrow: 'Agent Control',
    title: 'Review, approve, and rollback parser drafts',
    description: 'Inspect repair sessions, verify fixture behavior, and confirm version changes before they affect active runtime traffic.',
    refresh: 'Refresh',
    realtime: 'Realtime',
    connected: 'connected',
    disconnected: 'disconnected',
    adapters: 'Adapters',
    selectAdapter: 'Choose an adapter from the left panel to inspect its repair flow.',
    promoteCandidate: 'Approve Draft',
    rejectCandidate: 'Reject Draft',
    rollbackActive: 'Rollback Active',
    session: 'Session',
    activeVersion: 'Active Version',
    candidate: 'Review Draft',
    source: 'Source',
    repairMode: 'Repair Mode',
    versionHistory: 'Version History',
    noVersionHistory: 'No version history yet.',
    versionDetailsEmpty: 'Select a version to inspect its validation details.',
    repairContext: 'Repair Context',
    sessionId: 'Session ID',
    pageType: 'Page Type',
    triggerKey: 'Trigger Key',
    lastFailure: 'Last Failure',
    currentCandidate: 'Current Review Draft',
    sourceVersion: 'Source Version',
    autoTrigger: 'Auto Trigger Progress',
    failedProgress: 'Failure Count',
    remainingFailures: 'Remaining',
    cooldown: 'Cooldown',
    cooldownReady: 'Ready now',
    noTriggerProgress: 'No accumulated parsing failures yet.',
    versionCount: 'Versions',
    noAdapters: 'No registered adapter states yet.',
    validation: 'Validation',
    syntaxPassed: 'Syntax passed',
    syntaxFailed: 'Syntax failed',
    fixturesPassed: 'Fixtures Passed',
    fixturesFailed: 'Fixtures Failed',
    fixtureResults: 'Fixture Results',
    fixtureMatched: 'Fixture output matched the expected behavior.',
    noFixtureDetails: 'No fixture validation details recorded for this version.',
    basedOn: 'Based on',
    runtimeBaseline: 'runtime baseline',
    attemptSummary: 'Attempt {current} / {max}',
    pendingActions: {
      promoteTitle: 'Confirm draft approval',
      promoteDescription: 'This will promote {version} to the active runtime version for {adapterId}.',
      rejectTitle: 'Confirm draft rejection',
      rejectDescription: 'This will reject draft {version} and keep the current active version unchanged.',
      rollbackTitle: 'Confirm rollback',
      rollbackDescriptionWithVersion: 'This will roll {adapterId} back to {version}.',
      rollbackDescriptionWithoutVersion: 'This will roll {adapterId} back to the previous active version.',
      cancel: 'Cancel',
      confirm: 'Confirm',
      working: 'Working...',
    },
    statusLabels: {
      active: 'Active',
      candidate: 'Review Draft',
      rolled_back: 'Rolled back',
      rejected: 'Rejected',
      awaiting_review: 'Awaiting review',
      completed: 'Completed',
      failed: 'Failed',
      in_progress: 'In progress',
      running: 'Running',
      valid: 'Passed',
      invalid: 'Failed',
    },
  },
} satisfies UIText;
