export const uiText = {
  nav: {
    dashboard: '儀表板',
    tasks: '任務管理',
    search: '搜尋',
    settings: '設定',
    agent: '維護 Adapter',
    language: '語言',
  },
  language: {
    'zh-TW': '繁體中文',
    'en-US': 'English',
  },
  dashboard: {
    title: '儀表板',
    createTask: '建立任務',
    taskList: '任務列表',
    refresh: '重新整理',
    openManager: '開啟任務管理',
    adapterCapabilities: 'Adapter 能力',
    verificationCapability: '驗證外包 / Verification',
    metadataCapability: '漫畫目錄 / Metadata',
    chapterImagesCapability: '章節圖片 / Images',
    noAdapters: '尚未載入 adapter。',
  },
  taskForm: {
    urlLabel: 'URL',
    allChaptersMode: '全章節',
    allChaptersDescription: '輸入漫畫作品頁 URL，先抓作品資訊與章節清單，再下載全部章節圖片。',
    specificChaptersMode: '指定章節',
    specificChaptersDescription: '輸入一個或多個章節頁 URL，直接下載指定章節圖片，不先展開整部漫畫。',
    mangaUrlLabel: '漫畫 URL',
    mangaUrlHelp: '例如：https://kuronavi.one/manga/an-haxing-jian-guo-jia-noe-de-ling-zhu/',
    chapterUrlsLabel: '章節 URL',
    chapterUrlLabel: '章節 URL',
    chapterUrlsHelp: '每個輸入框填一個章節頁 URL；需要更多章節請按 + 新增輸入框。',
    addChapterUrl: '新增章節 URL',
    removeChapterUrl: '移除章節 URL',
    chaptersLabel: '章節篩選（選填，以逗號分隔）',
    chaptersPlaceholder: '例：第0章, 預告, #3, 51.2',
    chaptersHelp: '留空會下載全部章節。可填章節 ID、標題關鍵字、URL 片段；#3 代表抽出清單中的第 3 個項目。',
    priorityLabel: '優先權',
    priorityHelp: '只影響等待佇列排序，數字越大越早執行；不影響下載內容。',
    showAdvanced: '顯示進階選項',
    hideAdvanced: '隱藏進階選項',
    submit: '建立任務',
    submitting: '建立中...',
    created: '任務已建立。',
    viewTask: '查看任務',
    discoveryQueued: '未找到可用 adapter，已啟動 selector-discovery。',
    capabilityMismatch: '現有 adapter 能力不符合此任務',
    openDiscovery: '前往維護 Adapter 查看建立進度',
    discoveryNotCrawlerTask: '這是 Adapter 建立工作，不是爬蟲任務，因此不會出現在任務管理。',
    chapterOnlyDiscoveryQueued: '正在建立指定章節圖片能力。',
    fullDiscoveryQueued: '正在建立或補足全章節能力。',
  },
  taskList: {
    id: 'ID',
    url: 'URL',
    status: '狀態',
    priority: '優先權',
    actions: '操作',
    progress: '進度',
    empty: '目前沒有任務',
    pause: '暫停',
    resume: '繼續',
    cancel: '取消',
    delete: '刪除',
    view: '查看',
    statusLabels: {
      pending: '等待中',
      running: '執行中',
      waiting_verification: '等待人工驗證',
      completed: '已完成',
      failed: '失敗',
      paused: '已暫停',
      cancelled: '已取消',
      interrupted: '已中斷',
    },
  },
  taskManager: {
    title: '任務管理',
    description: '集中查看所有 task、進度快照與下載輸出預覽。',
    listTitle: '所有任務',
    detailTitle: '任務詳情',
    emptyState: '選擇一個 task 來查看詳細資訊。',
    noPreview: '這個 task 目前還沒有可顯示的下載預覽。',
    previewTitle: '下載預覽',
    outputPath: '輸出路徑',
    metadataTitle: '作品標題',
    downloadedImages: '已下載圖片',
    failedImages: '失敗圖片',
    totalImages: '總圖片數',
    currentItem: '目前項目',
    createdAt: '建立時間',
    startedAt: '開始時間',
    completedAt: '完成時間',
    error: '錯誤',
    files: '檔案',
    refresh: '重新整理',
  },
  stats: {
    loading: '載入中...',
    total: '全部任務',
    running: '執行中',
    waitingVerification: '等待驗證',
    pending: '等待中',
    interrupted: '已中斷',
    completed: '已完成',
    failed: '失敗',
    cancelled: '已取消',
  },
  search: {
    title: '搜尋漫畫',
    placeholder: '輸入關鍵字...',
    submit: '搜尋',
    submitting: '搜尋中...',
    empty: '查無結果',
    historyTitle: '最近搜尋',
  },
  settings: {
    title: '設定',
    loading: '載入中...',
    dismissError: '關閉錯誤',
    languageSection: '介面語言',
    languageLabel: '顯示語言',
    fallbackLabel: '備援語言',
    downloadSection: '下載設定',
    downloadDirectory: '下載目錄',
    downloadConcurrency: '下載並發數',
    namingTemplate: '命名模板',
    imageFormat: '圖片格式',
    originalFormat: '保留原始格式',
    networkSection: '網路設定',
    timeout: '逾時（毫秒）',
    retries: '重試次數',
    retryDelay: '重試延遲（毫秒）',
    save: '儲存一般設定',
    saveAoSettings: '儲存 AO 設定',
    selectorDiscoveryIndependentSave: 'Selector Discovery 使用獨立儲存，用於 AO URL、Provider JSON 與模型；一般設定的儲存按鈕不會保存此區塊。',
    reset: '重設為預設值',
  },
  agent: {
    eyebrow: 'Adapter 維護',
    title: '維護 Adapter 建立、審核與版本',
    description: '查看 Adapter 建立工作、審核解析版本，並在版本影響正式爬蟲前完成確認。',
    refresh: '重新整理',
    realtime: '即時連線',
    connected: '已連線',
    disconnected: '未連線',
    adapters: '站點 Adapter',
    selectAdapter: '從左側選擇一個 adapter 來檢查修復流程。',
    promoteCandidate: '升級候選版本',
    rejectCandidate: '拒絕候選版本',
    rollbackActive: '回滾目前版本',
    session: '修復 Session',
    activeVersion: '目前版本',
    candidate: '候選版本',
    source: '來源',
    repairMode: '修復模式',
    versionHistory: '版本歷史',
    noVersionHistory: '目前還沒有版本歷史。',
    versionDetailsEmpty: '選擇一個版本來查看驗證細節。',
    repairContext: '修復上下文',
    sessionId: 'Session ID',
    pageType: '頁面類型',
    triggerKey: '觸發鍵',
    lastFailure: '最近失敗原因',
    currentCandidate: '目前候選版本',
    sourceVersion: '來源版本',
    autoTrigger: '自動觸發進度',
    failedProgress: '失敗累積',
    remainingFailures: '距離觸發',
    cooldown: '冷卻時間',
    cooldownReady: '可立即觸發',
    noTriggerProgress: '目前還沒有累積中的解析失敗記錄。',
    versionCount: '版本數量',
    noAdapters: '目前尚未有已註冊的 adapter 狀態。',
    siteAdaptersTab: '站點 Adapter',
    buildJobsTab: 'Adapter 建立工作',
    capabilities: '能力',
    capabilityVerification: '驗證外包',
    capabilityMetadata: '漫畫目錄',
    capabilityChapterImages: '章節圖片',
    parseMode: 'DOM 策略',
    implementationKind: '實作來源',
    deleteAdapter: '刪除 Adapter',
    buildJobs: 'Adapter 建立工作',
    buildJobsDescription: '未知網站或能力不足時，ComicCrawler 會先建立 Adapter 能力；這些工作不會出現在任務管理。',
    noBuildJobs: '目前沒有 Adapter 建立工作。',
    buildJobTarget: '目標能力',
    buildJobMode: '建立模式',
    buildJobPhase: '階段',
    buildJobUpdated: '更新時間',
    buildJobUrl: '來源 URL',
    buildJobAdapter: 'Adapter',
    buildJobModel: '模型',
    buildJobAoUrl: 'AO URL',
    buildJobError: '錯誤',
    buildJobFull: '全章節能力 / Metadata + Chapter Images',
    buildJobChapterOnly: '指定章節能力 / Chapter Images',
    buildJobCreate: '建立新 Adapter',
    buildJobAugment: '補足既有 Adapter 能力',
    buildJobTaskBoundary: '這是 Adapter 建立工作，不是爬蟲任務；下載進度請到任務管理查看。',
    retryBuild: '重試建立',
    reviewAdapterDraft: '審核 Adapter draft',
    reviewPanelEyebrow: 'Adapter draft 審核',
    approveAdapter: '啟用 Adapter',
    rejectDraft: '拒絕 draft',
    editDraftCopy: '編輯副本',
    saveDraftCopy: '儲存副本',
    resetDraftCopy: '重設為原始 AO draft',
    editingDraftCopy: '你正在編輯 AO draft 的副本；原始 build job 仍保留等待審核。',
    unsavedDraftChanges: '有未儲存變更',
    agentFunctionRevision: '請 Agent 微調單一函式',
    agentFunctionRevisionDescription: '選定函式後，填寫希望怎麼修改。提交後會在這個 Adapter build job 下建立函式微調子任務；原 draft 不會被覆蓋。',
    functionRevisionPlaceholder: '例如：extractChapterList 應該只抓主章節列表，不要抓推薦區；請保留章節 URL 與標題。',
    submitFunctionRevision: '提交修改建議',
    functionRevisionCreated: '已建立函式微調子任務',
    functionRevisionRetryStarted: '已啟動函式微調子任務',
    runFunctionRevision: '執行 / 重試',
    functionRevisionTasks: '函式微調子任務',
    functionRevisionModelMode: '重試模型',
    functionRevisionModelCurrent: '目前 AO 設定',
    functionRevisionModelPrevious: '上次任務模型',
    functionRevisionSelfCheck: 'AO 自檢',
    closeReview: '關閉審核',
    reviewJobSummary: '工作摘要',
    capabilitiesAndFunctions: '能力與函式',
    implemented: '已實作',
    notImplemented: '未實作',
    loadingReview: '正在載入審核資料。',
    runDraftFunctionTest: '測試 draft 函式',
    testUrl: '測試 URL',
    runTests: '執行測試',
    testPassed: '測試通過',
    testFailed: '測試未通過',
    reviewNotes: 'Review notes',
    noReviewNotes: '這個 draft 沒有 review notes。',
    implementationValidation: 'Implementation validation',
    implementationSource: 'TypeScript implementation source',
    validation: '驗證結果',
    syntaxPassed: '語法檢查通過',
    syntaxFailed: '語法檢查失敗',
    fixturesPassed: '通過的 Fixture',
    fixturesFailed: '失敗的 Fixture',
    fixtureResults: 'Fixture 結果',
    fixtureMatched: 'Fixture 輸出與預期行為一致。',
    noFixtureDetails: '這個版本沒有記錄 fixture 驗證細節。',
    basedOn: '基於',
    runtimeBaseline: 'runtime baseline',
    attemptSummary: '第 {current} / {max} 次嘗試',
    implementationKinds: {
      'project-source': 'TypeScript source',
      'selector-manifest': 'Selector manifest',
      'ts-implementation': 'Generated TypeScript',
      summary: '摘要',
      'generated-draft': 'Generated draft',
    },
    pendingActions: {
      promoteTitle: '確認升級候選版本',
      promoteDescription: '這會把 {version} 升級成 {adapterId} 的正式 runtime 版本。',
      rejectTitle: '確認拒絕候選版本',
      rejectDescription: '這會拒絕候選版本 {version}，並保留目前正式版本不變。',
      rollbackTitle: '確認回滾',
      rollbackDescriptionWithVersion: '這會把 {adapterId} 回滾到 {version}。',
      rollbackDescriptionWithoutVersion: '這會把 {adapterId} 回滾到上一個正式版本。',
      deleteAdapterTitle: '確認刪除 Adapter',
      deleteAdapterDescription: '這會刪除 {adapterName}（{adapterId}）這個已註冊 Adapter。若它來自專案 TypeScript source，對應 source directory 也會被刪除；這屬於專案程式碼變更。',
      cancel: '取消',
      confirm: '確認',
      working: '處理中...',
    },
    statusLabels: {
      active: '正式版本',
      candidate: '候選版本',
      rolled_back: '已回滾',
      rejected: '已拒絕',
      awaiting_review: '等待審核',
      promoted: '已啟用',
      completed: '已完成',
      failed: '失敗',
      in_progress: '進行中',
      running: '執行中',
      queued: '等待中',
      configuration_required: '需要設定',
      known_adapter: '已有 Adapter',
      valid: '通過',
      invalid: '失敗',
    },
  },
} as const;

type DeepStringify<T> = {
  [K in keyof T]: T[K] extends string ? string : T[K] extends Record<string, unknown> ? DeepStringify<T[K]> : T[K];
};

export type UIText = DeepStringify<typeof uiText>;
